libraries:
  Movies:
    remove_overlays: false
    reapply_overlays: false
    report_path: /config/reports/movies_report.yml
    collection_files:
    - folder: /config/kometa_files/libraries/movies/collections/a24
    - folder: /config/kometa_files/libraries/movies/collections/bluesky_animation
#    - folder: /config/kometa_files/libraries/movies/collections/brainstorm
#    - folder: /config/kometa_files/libraries/movies/collections/buena_vista
#    - folder: /config/kometa_files/libraries/movies/collections/columbia
    - folder: /config/kometa_files/libraries/movies/collections/dc
    - folder: /config/kometa_files/libraries/movies/collections/dc/dceu
    - folder: /config/kometa_files/libraries/movies/collections/disney/animation
    - folder: /config/kometa_files/libraries/movies/collections/disney/live_action
    - folder: /config/kometa_files/libraries/movies/collections/disney/lucasfilm
    - folder: /config/kometa_files/libraries/movies/collections/disney/marvel/in_association_with
    - folder: /config/kometa_files/libraries/movies/collections/disney/marvel/marvel_studios
    - folder: /config/kometa_files/libraries/movies/collections/disney/marvel/ssu
    - folder: /config/kometa_files/libraries/movies/collections/disney/pixar
#    - folder: /config/kometa_files/libraries/movies/collections/disney/searchlight
    - folder: /config/kometa_files/libraries/movies/collections/dreamworks/
    - folder: /config/kometa_files/libraries/movies/collections/dreamworks/animation
    - folder: /config/kometa_files/libraries/movies/collections/elevation
#    - folder: /config/kometa_files/libraries/movies/collections/filmoption
#    - folder: /config/kometa_files/libraries/movies/collections/focus_features
#    - folder: /config/kometa_files/libraries/movies/collections/foton
    - folder: /config/kometa_files/libraries/movies/collections/fox
    - folder: /config/kometa_files/libraries/movies/collections/illumination
#    - folder: /config/kometa_files/libraries/movies/collections/invincible
    - folder: /config/kometa_files/libraries/movies/collections/lionsgate
#    - folder: /config/kometa_files/libraries/movies/collections/magnolia
#    - folder: /config/kometa_files/libraries/movies/collections/miramax
#    - folder: /config/kometa_files/libraries/movies/collections/megenta_light
    - folder: /config/kometa_files/libraries/movies/collections/netflix
    - folder: /config/kometa_files/libraries/movies/collections/new_line
    - folder: /config/kometa_files/libraries/movies/collections/paramount
#    - folder: /config/kometa_files/libraries/movies/collections/polygram
    - folder: /config/kometa_files/libraries/movies/collections/prime_video
#    - folder: /config/kometa_files/libraries/movies/collections/rlje
#    - folder: /config/kometa_files/libraries/movies/collections/saban
#    - folder: /config/kometa_files/libraries/movies/collections/screen_gems
#    - folder: /config/kometa_files/libraries/movies/collections/sky
    - folder: /config/kometa_files/libraries/movies/collections/sony
    - folder: /config/kometa_files/libraries/movies/collections/sony/animation
    - folder: /config/kometa_files/libraries/movies/collections/stx
#    - folder: /config/kometa_files/libraries/movies/collections/sumarian
#    - folder: /config/kometa_files/libraries/movies/collections/tristar
#    - folder: /config/kometa_files/libraries/movies/collections/we_go
    - folder: /config/kometa_files/libraries/movies/collections
    metadata_files:    
    - folder: /config/kometa_files/libraries/movies/metadata/a24
    - folder: /config/kometa_files/libraries/movies/metadata/appletv+
    - folder: /config/kometa_files/libraries/movies/metadata/bluesky_animation
    - folder: /config/kometa_files/libraries/movies/metadata/brainstorm
    - folder: /config/kometa_files/libraries/movies/metadata/buena_vista
    - folder: /config/kometa_files/libraries/movies/metadata/columbia 
    - folder: /config/kometa_files/libraries/movies/metadata/dc
    - folder: /config/kometa_files/libraries/movies/metadata/dc/dceu
    - folder: /config/kometa_files/libraries/movies/metadata/disney/animation
    - folder: /config/kometa_files/libraries/movies/metadata/disney/live_action
    - folder: /config/kometa_files/libraries/movies/metadata/disney/lucasfilm
    - folder: /config/kometa_files/libraries/movies/metadata/disney/marvel/in_association_with
    - folder: /config/kometa_files/libraries/movies/metadata/disney/marvel/marvel_studios
    - folder: /config/kometa_files/libraries/movies/metadata/disney/marvel/ssu
    - folder: /config/kometa_files/libraries/movies/metadata/disney/pixar
    - folder: /config/kometa_files/libraries/movies/metadata/disney/searchlight
    - folder: /config/kometa_files/libraries/movies/metadata/dreamworks/
    - folder: /config/kometa_files/libraries/movies/metadata/dreamworks/animation
    - folder: /config/kometa_files/libraries/movies/metadata/elevation
    - folder: /config/kometa_files/libraries/movies/metadata/filmoption
    - folder: /config/kometa_files/libraries/movies/metadata/focus_features
    - folder: /config/kometa_files/libraries/movies/metadata/foton
    - folder: /config/kometa_files/libraries/movies/metadata/fox
    - folder: /config/kometa_files/libraries/movies/metadata/illumination
    - folder: /config/kometa_files/libraries/movies/metadata/invincible
    - folder: /config/kometa_files/libraries/movies/metadata/laika
    - folder: /config/kometa_files/libraries/movies/metadata/lionsgate
    - folder: /config/kometa_files/libraries/movies/metadata/magnolia
    - folder: /config/kometa_files/libraries/movies/metadata/megenta_light
    - folder: /config/kometa_files/libraries/movies/metadata/miramax
    - folder: /config/kometa_files/libraries/movies/metadata/netflix
    - folder: /config/kometa_files/libraries/movies/metadata/new_line
    - folder: /config/kometa_files/libraries/movies/metadata/paramount
    - folder: /config/kometa_files/libraries/movies/metadata/polygram
    - folder: /config/kometa_files/libraries/movies/metadata/prime_video
    - folder: /config/kometa_files/libraries/movies/metadata/rlje
    - folder: /config/kometa_files/libraries/movies/metadata/saban
    - folder: /config/kometa_files/libraries/movies/metadata/screen_gems
    - folder: /config/kometa_files/libraries/movies/metadata/sky
    - folder: /config/kometa_files/libraries/movies/metadata/sony
    - folder: /config/kometa_files/libraries/movies/metadata/sony/animation
    - folder: /config/kometa_files/libraries/movies/metadata/stx
    - folder: /config/kometa_files/libraries/movies/metadata/sumarian
    - folder: /config/kometa_files/libraries/movies/metadata/tristar
    - folder: /config/kometa_files/libraries/movies/metadata/universal
    - folder: /config/kometa_files/libraries/movies/metadata/vertical
    - folder: /config/kometa_files/libraries/movies/metadata/warner_bros
    - folder: /config/kometa_files/libraries/movies/metadata/we_go
    - folder: /config/kometa_files/libraries/movies/metadata   
    overlay_files:
    - file: /config/kometa_files/overlays/movies/content_rating_us_movies.yml
      template_variables:
        use_nr: false
    - file: /config/kometa_files/overlays/movies/mediastinger.yml
    - file: /config/kometa_files/overlays/movies/ratings.yml
      template_variables:
        minimum_rating: 2.0
        rating1: critic
        rating1_image: rt_tomato
        rating2: audience
        rating2_image: rt_popcorn
        rating3: user
        rating3_image: trakt
    - file: /config/kometa_files/overlays/movies/resolution.yml
    - file: /config/kometa_files/overlays/movies/ribbons.yml
    operations:
#      schedule: weekly (friday)
#      mass_poster_update:
#        source: plex
      mass_genre_update:
      - tmdb
      mass_originally_available_update:
      - mdb
      - mdb_digital
      - 1900-01-01
      mass_critic_rating_update:
      - mdb_tomatoes
      - 1.0
      mass_audience_rating_update:
      - mdb_tomatoesaudience
      - 1.0
      mass_user_rating_update:
      - trakt_user
      - 1.0
      delete_collections:
        configured: false
        managed: false
        ignore_empty_smart_collections: false
        less: 2
  TV Shows:
    remove_overlays: false
    reapply_overlays: false
    report_path: /config/reports/tvshows_report.yml
    collection_files:
#    - folder: /config/kometa_files/libraries/series/collections/a&e
#    - folder: /config/kometa_files/libraries/series/collections/abc
#    - folder: /config/kometa_files/libraries/series/collections/amc
#    - folder: /config/kometa_files/libraries/series/collections/appletv+
#    - folder: /config/kometa_files/libraries/series/collections/bbcone
#    - folder: /config/kometa_files/libraries/series/collections/cbs
#    - folder: /config/kometa_files/libraries/series/collections/crave
#    - folder: /config/kometa_files/libraries/series/collections/ctv
    - folder: /config/kometa_files/libraries/series/collections/dc
    - folder: /config/kometa_files/libraries/series/collections/discovery
#    - folder: /config/kometa_files/libraries/series/collections/discovery+
#    - folder: /config/kometa_files/libraries/series/collections/disney
#    - folder: /config/kometa_files/libraries/series/collections/disney+
    - folder: /config/kometa_files/libraries/series/collections/disney+/marvel
    - folder: /config/kometa_files/libraries/series/collections/disney+/marvel/mcu
    - folder: /config/kometa_files/libraries/series/collections/disney+/star_wars    
#    - folder: /config/kometa_files/libraries/series/collections/fox
#    - folder: /config/kometa_files/libraries/series/collections/fx
#    - folder: /config/kometa_files/libraries/series/collections/hbo
    - folder: /config/kometa_files/libraries/series/collections/history
#    - folder: /config/kometa_files/libraries/series/collections/hulu
#    - folder: /config/kometa_files/libraries/series/collections/investigation_discovery
#    - folder: /config/kometa_files/libraries/series/collections/max
#    - folder: /config/kometa_files/libraries/series/collections/national_geographic
#    - folder: /config/kometa_files/libraries/series/collections/nbc
#    - folder: /config/kometa_files/libraries/series/collections/netflix
#    - folder: /config/kometa_files/libraries/series/collections/paramount+
#    - folder: /config/kometa_files/libraries/series/collections/peacock
#    - folder: /config/kometa_files/libraries/series/collections/prime_video
#    - folder: /config/kometa_files/libraries/series/collections/science
#    - folder: /config/kometa_files/libraries/series/collections/showtime
     - folder: /config/kometa_files/libraries/series/collections/shudder
#    - folder: /config/kometa_files/libraries/series/collections/sky_atlantic
#    - folder: /config/kometa_files/libraries/series/collections/starz
#    - folder: /config/kometa_files/libraries/series/collections/syfy
#    - folder: /config/kometa_files/libraries/series/collections/tnt
#    - folder: /config/kometa_files/libraries/series/collections/truetv
    - folder: /config/kometa_files/libraries/series/collections  
    metadata_files:
    - folder: /config/kometa_files/libraries/series/metadata/a&e
    - folder: /config/kometa_files/libraries/series/metadata/abc
    - folder: /config/kometa_files/libraries/series/metadata/amc
    - folder: /config/kometa_files/libraries/series/metadata/appletv+
    - folder: /config/kometa_files/libraries/series/metadata/bbcone
    - folder: /config/kometa_files/libraries/series/metadata/cbs
    - folder: /config/kometa_files/libraries/series/metadata/crave
    - folder: /config/kometa_files/libraries/series/metadata/ctv
    - folder: /config/kometa_files/libraries/series/metadata/dc
    - folder: /config/kometa_files/libraries/series/metadata/discovery
    - folder: /config/kometa_files/libraries/series/metadata/discovery+
    - folder: /config/kometa_files/libraries/series/metadata/disney
    - folder: /config/kometa_files/libraries/series/metadata/disney+
    - folder: /config/kometa_files/libraries/series/metadata/disney+/marvel
    - folder: /config/kometa_files/libraries/series/metadata/disney+/marvel/mcu
    - folder: /config/kometa_files/libraries/series/metadata/disney+/star_wars
    - folder: /config/kometa_files/libraries/series/metadata/fox
    - folder: /config/kometa_files/libraries/series/metadata/fx
    - folder: /config/kometa_files/libraries/series/metadata/hbo
    - folder: /config/kometa_files/libraries/series/metadata/history
    - folder: /config/kometa_files/libraries/series/metadata/hulu
    - folder: /config/kometa_files/libraries/series/metadata/investigation_discovery
    - folder: /config/kometa_files/libraries/series/metadata/max
    - folder: /config/kometa_files/libraries/series/metadata/national_geographic
    - folder: /config/kometa_files/libraries/series/metadata/nbc
    - folder: /config/kometa_files/libraries/series/metadata/netflix
    - folder: /config/kometa_files/libraries/series/metadata/paramount+
    - folder: /config/kometa_files/libraries/series/metadata/peacock
    - folder: /config/kometa_files/libraries/series/metadata/prime_video
    - folder: /config/kometa_files/libraries/series/metadata/science
    - folder: /config/kometa_files/libraries/series/metadata/showtime
    - folder: /config/kometa_files/libraries/series/metadata/shudder
    - folder: /config/kometa_files/libraries/series/metadata/sky_atlantic
    - folder: /config/kometa_files/libraries/series/metadata/starz
    - folder: /config/kometa_files/libraries/series/metadata/syfy
    - folder: /config/kometa_files/libraries/series/metadata/tnt
    - folder: /config/kometa_files/libraries/series/metadata/truetv
    - folder: /config/kometa_files/libraries/series/metadata      
    overlay_files:
    - file: /config/kometa_files/overlays/tvshows/content_rating_us_shows.yml
      template_variables:
        use_nr: false
    - file: /config/kometa_files/overlays/tvshows/mediastinger.yml
    - file: /config/kometa_files/overlays/tvshows/ratings.yml
      template_variables:
        minimum_rating: 2.0
        rating1: critic
        rating1_image: rt_tomato
        rating2: audience
        rating2_image: rt_popcorn
        rating3: user
        rating3_image: trakt
    - file: /config/kometa_files/overlays/tvshows/resolution.yml
    - file: /config/kometa_files/overlays/tvshows/ribbons.yml
    operations:
#      schedule: weekly (friday)
#      mass_poster_update:
#        source: plex
      mass_genre_update:
      - tmdb
      mass_originally_available_update:
      - tmdb
      - 2024-10-07
      mass_critic_rating_update:
      - mdb_tomatoes
      - 1.0
      mass_audience_rating_update:
      - mdb_tomatoesaudience
      - 1.0
      mass_user_rating_update: 
      - trakt_user
      - 1.0
      mass_episode_audience_rating_update:
      - tmdb
      - 1.0
      mass_episode_critic_rating_update:
      - imdb
      - 1.0
      delete_collections:
        configured: false
        managed: false
        ignore_empty_smart_collections: false
        less: 2
playlist_files:
- folder: /config/kometa_files/playlists
  schedule: daily
  template_variables:
    libraries: Movies, TV Shows
  delete_playlist: true
settings:
  run_order:
  - operations
  - metadata
  - overlays
  - collections
  cache: true
  cache_expiration: 14
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 3
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: sync
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: true
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: true
  show_options: true
  show_missing: false
  show_missing_assets: false
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: true
  custom_repo: https://github.com/Wikid82/kometa_files
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75
  show_unfiltered: false
webhooks:
  error: notifiarr
  version: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
  delete:
plex:
  # Can be individually specified per library as well; REQUIRED for the script to run
  url: <private>
  token: <private>
  timeout: 60
  db_cache:
  clean_bundles: true
  empty_trash: true
  optimize: true
  verify_ssl:
tmdb:
  # REQUIRED for the script to run
  apikey: <private>
  language: en
  cache_expiration: 7
  region:
tautulli:
  # Can be individually specified per library as well
  url: <private>
  apikey: <private>
github:
  token: <private>
omdb:
  apikey: <private>
  cache_expiration: 7
mdblist:
  apikey: <private>
  cache_expiration: 7
notifiarr:
  apikey: <private>
  #gotify:
  #  url: ##########
  #  token: ##########
  #anidb:
  # Not required for AniDB builders unless you want mature content
  #  username: ######
  #  password: ######
  #  language: en
  #  client: ##########
radarr:
  # Can be individually specified per library as well
  url: <private>
  token: <private>
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: <private>
  monitor: true
  availability: released
  quality_profile: BluRay 1080
  tag: kometa
  search: false
  radarr_path: /plex
  plex_path: /plex
  ignore_cache: false
sonarr:
  # Can be individually specified per library as well
  url: <private>
  token: <private>
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: <private>
  monitor: all
  quality_profile: '1080'
  language_profile: English
  series_type: standard
  season_folder: true
  tag: kometa
  search: false
  cutoff_search: false
  sonarr_path: /plex
  plex_path: /plex
  ignore_cache: false
trakt:
  client_id: <private>
  client_secret: <private>
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: <private>
    token_type: <private>
    expires_in: <private>
    refresh_token: <private>
    scope: public<private>
    created_at: <private>
