collections:
  Trainwreck Collection:
    collection_mode: hide_items
    collection_order: release
    tmdb_list_details: https://www.themoviedb.org/list/8546211-trainwreck
    url_background: https://api.mediux.pro/assets/0f846bec-4444-48ae-847d-16200cc9d8fb
    url_poster: https://raw.githubusercontent.com/Wikid82/kometa_files/refs/heads/main/images/collections/trainwreckcollection.webp
    # Trainwreck Collection Posters by Wikid82