collections:
  Ant-Man Collection:
    radarr_taglist: antman
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162886
  The Avengers Collection:
    radarr_taglist: avengers
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162894
  Captain America Collection:
    radarr_taglist: captainamerica
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162888
  Captain Marvel Collection:
    radarr_taglist: captainmarvel
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162889
  Doctor Strange Collection:
    radarr_taglist: doctorstrange
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162890
  The Guardians of the Galaxy Collection:
    radarr_taglist: gotg
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162891
  Iron Man Collection:
    radarr_taglist: ironman
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162892
  Thor Collection:
    radarr_taglist: thor
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162895
  Black Panther Collection:
    radarr_taglist: blackpanther
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/162887
  Avatar Collection:
    radarr_taglist: avatar
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/277976
  Baby Driver Collection:
    radarr_taglist: babydriver
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/158108
  Beauty and the Beast Collection:
    radarr_taglist: batb
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/44913
  Blade Collection:
    radarr_taglist: blade
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/12046
  The Bourne Collection:
    radarr_taglist: bourne
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/5420
  Cinderella Collection:
    radarr_taglist: cinderella
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/5420
  Die Hard Collection:
    radarr_taglist: diehard
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/719
  Dune Collection:
    radarr_taglist: dune
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/197348
  Enola Holmes Collection:
    radarr_taglist: enola
    collection_order: release.asc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/299670





