metadata:
  1477453: # Trainwreck: The Astroworld Tragedy (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/34674
    url_poster: https://api.mediux.pro/assets/91fe151e-3ece-4a46-8c9c-ac62449ddc36
    url_background: https://api.mediux.pro/assets/0f846bec-4444-48ae-847d-16200cc9d8fb

  1484255: # Trainwreck: Mayor of Mayhem (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/34675
    url_poster: https://api.mediux.pro/assets/7f175bc3-97bf-4775-8261-324b02b2461f
    url_background: https://api.mediux.pro/assets/a3a5b327-d0ce-4c45-a32e-70c7992b0444
