metadata:
  1477453: # Trainwreck: The Astroworld Tragedy (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/34674
    url_poster: https://api.mediux.pro/assets/91fe151e-3ece-4a46-8c9c-ac62449ddc36
    url_background: https://api.mediux.pro/assets/0f846bec-4444-48ae-847d-16200cc9d8fb
