metadata:
  1477453: # Trainwreck: The Astroworld Tragedy (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/34674
    url_poster: https://api.mediux.pro/assets/91fe151e-3ece-4a46-8c9c-ac62449ddc36
    url_background: https://api.mediux.pro/assets/0f846bec-4444-48ae-847d-16200cc9d8fb

  1484255: # Trainwreck: Mayor of Mayhem (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/34675
    url_poster: https://api.mediux.pro/assets/7f175bc3-97bf-4775-8261-324b02b2461f
    url_background: https://api.mediux.pro/assets/a3a5b327-d0ce-4c45-a32e-70c7992b0444

  1484253: # Trainwreck: Poop Cruise (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/34677
    url_poster: https://api.mediux.pro/assets/c25458ad-4caa-4c74-a3fe-ab7c65faca0a
    url_background: https://api.mediux.pro/assets/08a0912f-d55b-4a32-879c-1e9115b43855

  1484262: # Trainwreck: The Cult of American Apparel (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/35049
    url_poster: https://api.mediux.pro/assets/4c94951c-fc05-40b6-a154-15acffe71fa5
    url_background: https://api.mediux.pro/assets/59d10ef3-d3be-4f82-8837-ad72c3a09364

  1477565: # Trainwreck: The Real Project X (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/35150
    url_poster: https://api.mediux.pro/assets/9b34a90d-25ac-4c88-b509-27a3db16a8df
    url_background: https://api.mediux.pro/assets/24540416-41ac-42c5-893c-9dfe352de132

  1477566: # Trainwreck: Balloon Boy (2025) Poster by Wikid82 on MediUX. https://mediux.pro/sets/35151
    url_poster: https://api.mediux.pro/assets/76f1efaa-9273-44de-860c-fc6c834f31fd
    url_background: https://api.mediux.pro/assets/17043667-43df-4bb6-b4d0-7f1d20934029

