metadata:
  Trainspotting:
    mapping_id: 627
    url_poster: https://api.mediux.pro/assets/c73bff77-27e4-4324-a78e-20df3b913004
  T2 Trainspotting:
    mapping_id: 180863
    url_poster: https://api.mediux.pro/assets/d32a501b-2620-4f27-9aaa-299242bdd649
