collections:
  Trainwreck Collection:
    collection_mode: hide_items
    collection_order: release
    tmdb_collection_details: https://www.themoviedb.org/collection/731067-bird-box-collection
    url_background: https://api.mediux.pro/assets/0f846bec-4444-48ae-847d-16200cc9d8fb
    url_poster: https://raw.githubusercontent.com/Wikid82/kometa_files/refs/heads/main/images/collections/trainwreckcollection.jpg
    # Trainwreck Collection Posters by Wikid82